@entryService = http://localhost:3001
###
POST {{entryService}}/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{"description":"no description","date":"2015-01-22","specialist":"McDonald","healthCheckRating":0,"type":"HealthCheck","diagnosisCodes":["S62.5"]}

###
POST {{entryService}}/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{"description":"no description","date":"2015-01-22","specialist":"McDonald","healthCheckRating":9,"type":"HealthCheck","diagnosisCodes":["S62.5"]}
