@patientorService = http://localhost:3001
###
GET {{patientorService}}/api/patients

###
GET {{patientorService}}/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667

###
POST {{patientorService}}/api/patients
Content-Type: application/json

{"dateOfBirth":"1996-06-30","gender":"male","name":"Noname","occupation":"no job","ssn":"secret"}
