@patientorService = http://localhost:3001

###
GET {{patientorService}}/api/patients

###
POST {{patientorService}}/api/patients
Content-Type: application/json

{"dateOfBirth":"1996-06-30","gender":"male","name":"Noname","occupation":"no job","ssn":"secret"}
